version: '3'
services:
  selenium:
    container_name: selenium
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"
    volumes:
      - ./selenium:/selenium
    networks:
      - selenium_net
  app:
    container_name: app
    build: app/
    volumes:
      - ./app:/app
    ports:
      - "3030:3030"
    depends_on:
      - selenium
      - ch-client
    networks:
      - selenium_net
      - clickhouse_net
    command: python3 main.py
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - ch-server
    networks:
      - clickhouse_net
  ch-server:
    container_name: ch-server
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
    networks:
      - clickhouse_net
  ch-client:
    container_name: ch-client
    image: yandex/clickhouse-client:latest
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    networks:
      - clickhouse_net
    depends_on:
      - ch-server
networks:
  clickhouse_net:
    driver: bridge
  selenium_net:
    driver: bridge
volumes:
  grafana-data: